package org.dync.tv.teameeting.structs;


public enum EventType {
    MSG_RESPONS_ESTR_NULl,
    MSG_GET_MEETING_INFO_SUCCESS,
    MSG_GET_MEETING_INFO_FAILED,
    MSG_GET_ROOM_LIST_SUCCESS,
    MSG_GET_ROOM_LIST_FAILED,
    MSG_INSERT_USER_MEETING_ROOM_SUCCESS,
    MSG_INSERT_USER_MEETING_ROOM_FAILED,
    MSG_UP_DATE_USER_MEETING_JOIN_TIME_SUCCESS,
    MSG_UP_DATE_USER_MEETING_JOIN_TIME_FAILED,
    MSG_CALL_ME_START,
    MSG_CALL_ME_STOP,
    MSG_CALL_START,
    MSG_CALL_STOP,
    MSG_BTN_ENTER_JOIN_MEETING,
    MSG_NOTIFY_DATA_CHANGE,

}
